ci: skip benches in datadog-profiling-core
It doesn't have any, but it can fail with messages like:
> error: Unrecognized option: 'warm-up-time'
If we don't set benches=false