fix(ci): skip thread counting test (#1841)
# What does this PR do?
`test_count_active_threads` run on centos7 are [flaking](https://github.com/DataDog/libdatadog/actions/runs/23868297465/job/69593217671?pr=1839) as such:
```
stdout ───

    running 1 test

    running 1 test

    thread 'test_utils::tests::test_count_active_threads' (70243) panicked at libdd-common/src/test_utils.rs:564:13:
    Expected thread count to return to 2 or 3 after join, got 4
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    test test_utils::tests::test_count_active_threads ... FAILED

    failures:

    failures:
        test_utils::tests::test_count_active_threads

    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 112 filtered out; finished in 0.05s

  stderr ───

    thread 'test_utils::tests::test_count_active_threads' (70241) panicked at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rusty-fork-0.3.1/src/fork_test.rs:135:9:
    child exited unsuccessfully with exit status: 70
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is because some platforms, such as CentOS, spawn helper threads

# Motivation

Its been extremely flaky over the past two months

# Additional Notes

This test test a helper that is used for another test. The actual thread counting functionality seems sound, but the testing of thread counting with hard assertions on the # of threads is flaky because it is dependent on platform and sync state

# How to test the change?

Describe here in detail how the change can be validated.


Co-authored-by: edmund.kump <edmund.kump@datadoghq.com>