fix(ci): pin RUSTUP_TOOLCHAIN (#2041)
# What does this PR do?

Pin rustup toolchain version

# Motivation

```
error: failed to compile `cargo-public-api v0.50.2`, intermediate artifacts can be found at `/tmp/cargo-installU0E62f`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  rustc 1.87.0 is not supported by the following package:
    home@0.5.12 requires rustc 1.88
```

---------

Co-authored-by: Claude Opus 4.7 <noreply@anthropic.com>