Fix build error due to "set_http1_header_read_timeout" not being found
Without this tweak, I was getting

```
   Compiling hyper v0.14.28
error[E0599]: no method named `set_http1_header_read_timeout` found for struct `Conn` in the current scope
   --> /home/ivo.anjo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.28/src/server/conn/http1.rs:374:18
    |
374 |             conn.set_http1_header_read_timeout(header_read_timeout);
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `Conn<I, _, _>`
    |
   ::: /home/ivo.anjo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.28/src/proto/h1/conn.rs:34:1
    |
34  | pub(crate) struct Conn<I, B, T> {
    | ------------------------------- method `set_http1_header_read_timeout` not found for this struct
```

and indeed this method is

```rust
    #[cfg(all(feature = "server", feature = "runtime"))]
    pub(crate) fn set_http1_header_read_timeout(&mut self, val: Duration) {
        self.state.h1_header_read_timeout = Some(val);
    }
```