fix(ipc)!: `AtomicOption` -> `AtomicOptionBox` to fix potential undefined behaviors (#2618)
# What does this PR do?

EDIT: This was the original description, left for the record.

> This PR moves some debug-only layout safety checks (causing UB if violated) to enforce them always at compile time. It also restricts previous behavior which could cause UB (undected by the previous check) for the `AtomicOption` type: `atomic_swap` rounded sizes 3 and 5-7 up to the next atomic width without padding (any write on this would touch unrelated, out-of-bounds accesses), and assumed that `Option<T>` is at least as aligned as that atomic, which doesn't hold e.g. for `Option<u32>` (size 8, align 4) or `Option<[u8; 3]>` (size 4, align 1). All of this was reachable from safe code.

However, adding tests show that there's a _third_ UB which is not easy to get rid of:

```
error: Undefined Behavior: constructing invalid value of type std::option::Option<std::boxed::Box<std::string::String>>: at .<enum-variant(Some)>.0, encountered a dangling box (0x181148[noalloc] has no provenance)
       --> libdd-ipc/src/atomic_option.rs:129:13
        |
    129 |             result.assume_init()
        |             ^^^^^^^^^^^^^^^^^^^^ Undefined Behavior occurred here
        |
        = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
        = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
        = note: this is on thread `atomic_option::`
        = note: stack backtrace:
```

It seems it is UB to just copy in and out a `Box<...>` as an unsigned int because of the new provenance API. This one is more painful to eliminate, and the only actual production use of `AtomicOption` _does_ put a `Box` in it.

The current version of this PR thus changes `AtomicOption` to a more specialized `AtomicOptionBox`, which uses an `AtomicPtr` under the hood and thus properly handle provenance questions. Since it's only used in `ShMem`, the callsites are fine. This also sidesteps the issue of `T` having uninitialized padding, since we use a proper atomic pointer and not an integer under the hood. In fact it sidesteps all layout issues in general, since `Option<Box<T>>` and `AtomicPtr<T>` are guaranteed to have an identical layout.

Finally, this gets rid of useless code as a net diff.

# Motivation

I'm triaging potentially UB code flagged by an LLM. This one is 1. legit UB 2. easy to fix (amended: somehow. Less easy than initially planned :upside_down_face: ).

# How to test the change?

See added tests.

Co-authored-by: yann.hamdaoui <yann.hamdaoui@datadoghq.com>